// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5CjYHKG6jsxj-FIDnF3Tz3wOnfc48-Qc',
    appId: '1:1091878583094:web:0f3230e49e840789de1197',
    messagingSenderId: '1091878583094',
    projectId: 'doctors-854c5',
    authDomain: 'doctors-854c5.firebaseapp.com',
    storageBucket: 'doctors-854c5.firebasestorage.app',
    measurementId: 'G-R3TVKFS5VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-WpJFDAuwOOKCT38QsWJyZ-s-RZouzN8',
    appId: '1:1091878583094:android:86424cc52cfe3074de1197',
    messagingSenderId: '1091878583094',
    projectId: 'doctors-854c5',
    storageBucket: 'doctors-854c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADy2iYytvFaRGrYdqQTQKYOh5NRv45fqU',
    appId: '1:1091878583094:ios:74853f4a012cfad7de1197',
    messagingSenderId: '1091878583094',
    projectId: 'doctors-854c5',
    storageBucket: 'doctors-854c5.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADy2iYytvFaRGrYdqQTQKYOh5NRv45fqU',
    appId: '1:1091878583094:ios:74853f4a012cfad7de1197',
    messagingSenderId: '1091878583094',
    projectId: 'doctors-854c5',
    storageBucket: 'doctors-854c5.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5CjYHKG6jsxj-FIDnF3Tz3wOnfc48-Qc',
    appId: '1:1091878583094:web:078a534371f31b30de1197',
    messagingSenderId: '1091878583094',
    projectId: 'doctors-854c5',
    authDomain: 'doctors-854c5.firebaseapp.com',
    storageBucket: 'doctors-854c5.firebasestorage.app',
    measurementId: 'G-8T8NCE2Z9N',
  );
}
